trigger:
  - main  # ou a branch que você quer monitorar

pool:
  vmImage: 'ubuntu-latest'  # ou outra imagem que você preferir

steps:
  - checkout: self  # Clona o repositório

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Especifique a versão do Python
      addToPath: true

  - script: |
      python -m pip install -r requirements.txt  # Instala dependências
      python sprint4.py  # Executa o script Python
    displayName: 'Run Python script'
