
trigger:
  branches:
    include:
      - main  # Branch que aciona a pipeline

pool:
  vmImage: 'ubuntu-latest'  # Máquina virtual que vai executar o pipeline

steps:
- checkout: self  # Faz o checkout do código do repositório (padrão)

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt  # Instalar dependências
    python main.py                   # Executar seu código Python
  displayName: 'Instalar dependências e rodar código'
